### ISSUE TITLE
Daily County Case Count Data XLSX moved

### ISSUE THREAD

**Issue by captbrando** [arencambre/texascovidstats#9]
https://www.dshs.state.tx.us/coronavirus/TexasCOVID19DailyCountyCaseCountData.xlsx

I have emailed the web folks to see if they have an updated file.

**Comment by arencambre** [comment]
That may explain why the last successful run was 8 AM on August 25. On occasion, they change filenames. Let me know what you find out.

**Comment by captbrando** [comment]
Just heard back. Looks like a no go for automated pulls of daily stats. Here's the email I got back:

---

Beginning this week, the attached data files will only be updated weekly and provided by request via email. However, the cumulative confirmed and probable cases and fatalities by county are updated every day Monday-Friday in the following Excel file and on the COVID-19 dashboard.

* Accessible Dashboard Excel file: [https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx](https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx)
* COVID-19 Dashboard: [https://www.arcgis.com/apps/dashboards/45e18cba105c478697c76acbbf86a6bc](https://www.arcgis.com/apps/dashboards/45e18cba105c478697c76acbbf86a6bc)

Let us know if you need anything else,

**Comment by arencambre** [comment]
Got it. This makes sense. I think the pandemic phase has run its course, and we switched to the endemic phase months ago despite no "official" word. I probably need to mothball this script.
